
version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - 5001:80  # host:container
    depends_on:
      - brevet

  brevet:
    build: ./brevet

    command: python -u app.py
    ports:
      - "5005:5000"
    volumes:
      - ./brevet:/todo
    links:
      - db

  db:
    image: mongo:3.0.2

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5000:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running